db:
    image: mongo
    ports:
        - 27017:27017/tcp
web:
    build: .
    command: gulp serve
    volumes:
        - .:/usr/src/app
    ports:
        - 5000:5000/tcp
    links:
        - db
    environment:
        PORT: 5000
